### ISSUE TITLE
`require': cannot load such file -- activeadmin/axlsx (LoadError)

### ISSUE THREAD

**Issue by tinkesh** [randym/activeadmin-axlsx#30]
Hi, 

In my gem file 
gem 'activeadmin'
gem 'activeadmin-axlsx'

When I run bundle install, all the required gems got installed. But when I start the run "rails s" I am getting below error.

/home/rails/.rvm/gems/ruby-1.9.3-p125/gems/bundler-1.1.3/lib/bundler/runtime.rb:74:in `require': cannot load such file -- activeadmin/axlsx (LoadError)
    from /home/user1/.rvm/gems/ruby-1.9.3-p125/gems/bundler-1.1.3/lib/bundler/runtime.rb:74:in`rescue in block in require'
    from /home/user1/.rvm/gems/ruby-1.9.3-p125/gems/bundler-1.1.3/lib/bundler/runtime.rb:62:in `block in require'
    from /home/user1/.rvm/gems/ruby-1.9.3-p125/gems/bundler-1.1.3/lib/bundler/runtime.rb:55:in`each'
    from /home/user1/.rvm/gems/ruby-1.9.3-p125/gems/bundler-1.1.3/lib/bundler/runtime.rb:55:in `require'
    from /home/user1/.rvm/gems/ruby-1.9.3-p125/gems/bundler-1.1.3/lib/bundler.rb:119:in`require'
    from /home/user1/Workspace/audit_management/with_admin/audit/config/application.rb:7:in `<top (required)>'
    from /home/user1/.rvm/gems/ruby-1.9.3-p125/gems/railties-3.2.13/lib/rails/commands.rb:53:in`require'
    from /home/user1/.rvm/gems/ruby-1.9.3-p125/gems/railties-3.2.13/lib/rails/commands.rb:53:in `block in <top (required)>'
    from /home/user1/.rvm/gems/ruby-1.9.3-p125/gems/railties-3.2.13/lib/rails/commands.rb:50:in`tap'
    from /home/user1/.rvm/gems/ruby-1.9.3-p125/gems/railties-3.2.13/lib/rails/commands.rb:50:in `<top (required)>'
    from script/rails:6:in`require'
    from script/rails:6:in `<main>'

Can any one help me on this?

**Comment by zurzer** [comment]
first download it from github to change something.
git clone https://github.com/randym/activeadmin-axlsx
git clone https://github.com/ywencn/active_admin

make path correct.
gem 'activeadmin-axlsx', path: '../activeadmin-axlsx'
gem 'activeadmin', path: '../activeadmin'

change all below:

for undefined method `xlsx' for #ActiveAdmin::ResourceDSL:0x (NoMethodError)
yourproject/config/environments/production.rb
    set
    config.eager_load = false

for `require': cannot load such file -- activeadmin/axlsx (LoadError) 
activeadmin-axlsx/activeadmin-axlsx.gemspec
  s.add_runtime_dependency 'activeadmin', "~> 0.6.0"
  to
  s.add_runtime_dependency 'activeadmin', "> 0.6.0"

for ArgumentError (wrong number of arguments (1 for 0)):
activeadmin/lib/active_admin/resource_controller/streaming.rb:11:in `index'
    Change line 11
    def index
    to
    def index(arg=nil)

for undefined local variable or method `max_csv_records':
activeadmin-axlsx/lib/active_admin/axlsx/resource_controller_extension.rb:11:in`per_page_with_xlsx'
    add max_csv_records = 1000 # some num which result in db query as limit 1000 in the end of select \* query.

```
  def per_page_with_xlsx
      max_csv_records = 1000   #add
      if request.format ==  Mime::Type.lookup_by_extension(:xlsx)
        return max_csv_records
      end
      per_page_without_xlsx
  end
```
